### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by kbresin** [devsr/plex-selinux#1]
README says the command to add a permanent file context is:

> $ semanage fcontext -a -t plex_content_t "/usr/share/my_media_library(/*.)?"

the "STAR-DOT" is backwards, should be "DOT-STAR":

semanage fcontext -a -t plex_content_t "/usr/share/my_media_library(/.*)?"

**Comment by devsr** [comment]
Fixed! Thanks for the report @kbresin
