### ISSUE TITLE
Needed to add execstack and execmem for plexmediaserver-0.9.12.1.1079-b655370.x86_64

### ISSUE THREAD

**Issue by kbresin** [devsr/plex-selinux#2]
I had to change the line:

> allow plex_t self:process { getcap setcap signal_perms setsched  };

to

> allow plex_t self:process { getcap setcap signal_perms setsched execstack execmem };

in plex.te to get the server to start up on CentOS 6.6, plex version plexmediaserver-0.9.12.1.1079-b655370.x86_64

Don't know if there is a more confined way to enable that (it is what allow2audit suggested).

Thanks again for this!

**Comment by devsr** [comment]
Thanks for the report @kbresin . I'll take a look at this. My understanding is that properly written programs should not require execstack or execmem.

Can you post relevant AVC notices from the audit log?

A description of how/when it happened would be helpful as well. Was this on first run of a fresh Plex install or did this occur after an update? If it was an update did you update using the Web UI or did you update RPM?

**Comment by kbresin** [comment]
Sure thing, here are the AVC notices:

type=AVC msg=audit(1433183576.059:16793): avc:  denied  { execstack } for  pid=10796 comm=506C6578204D656469612053657276 scontext=unconfined_u:system_r:plex_t:s0 tcontext=unconfined_u:system_r:plex_t:s0 tclass=process

type=AVC msg=audit(1433180602.716:16689): avc:  denied  { execmem } for  pid=9513 comm=506C6578204D656469612053657276 scontext=unconfined_u:system_r:plex_t:s0 tcontext=unconfined_u:system_r:plex_t:s0 tclass=process

execstack was first.  After I modified the policy to allow execstack for t_plex, then it starting giving the execmem denied.

This was on, essentially, a fresh install of plex, and the errors happened when I attempted to start plex:

service plexmediaserver start

It would say it succeeded, but nothing (no processes) would start.

The nonsense hex command (comm=) confuses me, and I couldn't quite track down which of the services in startup were doing it.

**Comment by devsr** [comment]
The execstack issue seems to have been reported by others as well. Seems like Plex may be using a library with it. Plex needs to fix this upstream, in the meantime the policy can be modified to allow it.

https://forums.plex.tv/index.php/topic/160270-pms-0912-on-selinux/

I'll confirm locally and then edit the policy as needed.

**Comment by devsr** [comment]
The problem library is `/usr/lib/plexmediaserver/libgnsdk_dsp.so.3.07.5`. For some reason it has execstack set. 

execstack flag can be cleared from the library by using the 'execstack' tool (requires prelink package) as root.

```
# execstack -c /usr/lib/plexmediaserver/libgnsdk_dsp.so.3.07.5
```

Once done, SELinux should no longer complain about execstack or execmem.

No policy edits are required. @kbresin If you want to confirm this on your end, I'll close this out (remember to revert to the unchanged policy when testing).

**Comment by kbresin** [comment]
Confirmed!

I revoked execstack from that library as written, reloaded the plex policy without execstack and execmem and it started up just fine.

Thanks for the research.

Do you mind me asking how you tracked it down to that library? (I'm just curious.)

**Comment by devsr** [comment]
Updated the README and closing this one out. Thanks for the report!

**Comment by devsr** [comment]
@kbresin, To answer your question, in the plex forum thread I linked earlier someone indicated that library had execstack set. Also when I tried it locally, journalctl logs had a linking error with that library as well. To confirm `execstack` with a `-q` option can be used to query the execstack flag on a library.
